sudo: false
language: ruby
rvm:
- jruby-9.1.2.0
- 1.9.3
- 2.0.0-p648
- 2.2.5
- 2.3.1
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile
env:
  matrix:
  - JQUERY_VERSION=1.11.1
  - JQUERY_VERSION=2.1.1
  - JQUERY_VERSION=3.1.0

script: bundle exec rspec spec

before_install:
  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
