sudo: false
language: ruby
rvm:
- jruby-9.1.2.0
- 1.9.3
- 2.0.0-p648
- 2.2.5
- 2.3.1
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.gemfile
env:
  matrix:
  - JQUERY_VERSION=1.12.4
  - JQUERY_VERSION=2.2.4
  - JQUERY_VERSION=3.1.0
matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/rails_5.gemfile
  - rvm: 2.0.0-p648
    gemfile: gemfiles/rails_5.gemfile

script: bundle exec rspec spec

before_install:
  - mkdir travis-phantomjs
  - wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
